services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: twitterdb
      POSTGRES_USER: twitter
      POSTGRES_PASSWORD: twitter
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 15

  backend:
    build: ./backend
    working_dir: /app
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_DB: twitterdb
      POSTGRES_USER: twitter
      POSTGRES_PASSWORD: twitter
      DB_HOST: db
      DB_PORT: 5432
      DJANGO_SECRET_KEY: dev-secret-change-me
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - media:/app/media
    command: >
      sh -c "
        until pg_isready -h db -p 5432 -U $POSTGRES_USER; do
          echo 'Aguardando Postgres...'; sleep 1;
        done &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "

volumes:
  pgdata:
  media:
