services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: twitterdb
      POSTGRES_USER: twitter
      POSTGRES_PASSWORD: twitter
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 15

  backend:
    build: ./backend
    working_dir: /app
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_DB: twitterdb
      POSTGRES_USER: twitter
      POSTGRES_PASSWORD: twitter
      DB_HOST: db
      DB_PORT: 5432
      DJANGO_SECRET_KEY: dev-secret-change-me
      DJANGO_DEBUG: "true"
      DJANGO_SECURE_SSL_REDIRECT: "false"
      ALLOWED_HOSTS: "*"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - media:/app/media
    command: >
      sh -c "
        until pg_isready -h db -p 5432 -U $$POSTGRES_USER; do
          echo 'Aguardando Postgres...'; sleep 1;
        done &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend-react:/app
    environment:
      VITE_API_BASE: "http://127.0.0.1:8000/api/"
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "5173:5173"
    command: >
      sh -c "
        if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then npm ci; else npm i; fi &&
        npm run dev -- --host 0.0.0.0 --port 5173
      "

volumes:
  pgdata:
  media:
